# Generated by Django 4.1.7 on 2023-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_newevent_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collageinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collagename', models.CharField(max_length=122)),
                ('achivment', models.DateTimeField()),
                ('collageurl', models.URLField()),
                ('detail', models.CharField(max_length=122)),
            ],
        ),
    ]
