# Generated by Django 4.1.7 on 2023-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_collageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collageinfo',
            name='achivment',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='collageinfo',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
    ]
