# Generated by Django 4.1.7 on 2023-04-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_collageinfo_achivment_alter_collageinfo_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, unique=True)),
                ('department_hod_name', models.SlugField(max_length=100, unique=True)),
                ('department_teachingstaff', models.IntegerField()),
                ('department_nonteachingstaff', models.IntegerField()),
                ('department_fees', models.IntegerField()),
            ],
        ),
    ]
