# Generated by Django 4.1.6 on 2023-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=122)),
                ('Lname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
            ],
        ),
    ]
